name: Model CI / CD
on: workflow_dispatch # evento que dispara el workflow, en este caso manualmente
jobs:
  model-ci:
    runs-on: ubuntu-latest # en qué runner va a correr el job
    steps:
      - name: Get Code
        uses: actions/checkout@v4 #repositorio/action@version
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name : Install Python Dependecies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  
      - name: Split Dataset
        run: python scr/0-split-dataset.py
      #- name: Test model
      #  run: echo "Test model"