name: Model CI / CD
on: workflow_dispatch # evento que dispara el workflow, en este caso manualmente
jobs:
  model-ci:
    runs-on: ubuntu-latest # en qué runner va a correr el job
    steps:
      - name: Get Code
        uses: actions/checkout@v4 #repositorio/action@version
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name : Install Python Dependecies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  
      - name: Split Dataset
        run: python src/0-split-dataset.py
      - name: Preprocess Data
        run: python src/1-preprocess-dataset-train.py
      - name: Prepare Dataset Test
        run: python src/2-prepare-dataset-test.py
      - name: Built Model
        run: echo "Build model"

  model-cd:
    needs: model-ci # el segundo job depende del primero
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Deploy model
        run: echo "Deploy model to AWS"