name: My First Workflow
on: workflow_dispatch # evento que dispara el workflow, en este caso manualmente
jobs:
  first-job:
    runs-on: ubuntu-latest # en qué runner va a correr el job
    steps:
      - name: Print Greetings
        run: echo "Hello world!" #echo es como un print en bash
      - name: Print Multiple lines
        run: |
          echo "First Line ..."
          echo "This is my first workflow"
          echo "I am learning GitHub Actions"
      - name: Print Goodbye
        run: echo "Goodbye!"