name: My Second Workflow
on: [workflow_dispatch, push] # evento que dispara el workflow, en este caso manualmente y al hacer push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4 #repositorio/action@version
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Verify Python
        run: python --version
      - name: Test model
        run: echo "Test model"
  
  second-job:
    needs: first-job # el segundo job depende del primero
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Deploy model
        run: echo "Deploy model to AWS"